spring:
  application:
    name: jwt

mxzero:
  security:
    config:
      jwt:
        sign: test
        issuer: test
        secret: test
        expire: 3600 # 单位：秒
      password:
        encrypt:
          repeat: test
          salt: test